export const GET_VEHICLE_LIST = "GET_VEHICLE_LIST";
export const GET_VEHICLE_LIST_SUCCESS = "GET_VEHICLE_LIST_SUCCESS";
export const GET_VEHICLE_LIST_FAILURE = "GET_VEHICLE_LIST_FAILURE";

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';

export const GET_VEHICLE_BY_ID = "GET_VEHICLE_BY_ID";
export const GET_VEHICLE_BY_ID_SUCCESS = "GET_VEHICLE_BY_ID_SUCCESS";
export const GET_VEHICLE_BY_ID_FAILURE = "GET_VEHICLE_BY_ID_FAILURE";

export const GET_VEHICLES_BY_BRAND = "GET_VEHICLES_BY_BRAND";
export const GET_VEHICLES_BY_BRAND_SUCCESS = "GET_VEHICLES_BY_BRAND_SUCCESS";
export const GET_VEHICLES_BY_BRAND_FAILURE = "GET_VEHICLES_BY_BRAND_FAILURE";