import Head from 'next/head';
import { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getVehicleList, setCurrentPage } from '@/store/vehicle/actions';
import { CarCard } from '@/components';
import { VehicleInterface } from '@/utils/interfaces';

export default function Home() {
  const vehicles = useSelector((state: any) => state.vehicles);
  const currentPage = useSelector((state: any) => state.vehicles.currentPage);
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(getVehicleList(currentPage));
  }, [dispatch, currentPage]);

  const handlePageChange = (newPage: number) => {
    dispatch(setCurrentPage(newPage));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="p-4">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
            {vehicles.vehicleList.map((vehicle: VehicleInterface, index: number) => (
              <CarCard key={vehicle.id} car={vehicle} />
            ))}
          </div>

          <div className="sticky bottom-0 bg-white py-4 px-4 flex justify-center mt-2">
            <button
              onClick={() => handlePageChange(currentPage - 1)}
              disabled={currentPage === 1}
              className="px-4 py-2 bg-black text-white rounded-md mr-2"
            >
              Previous
            </button>
            <button
              onClick={() => handlePageChange(currentPage + 1)}
              disabled={currentPage === 3}
              className="px-4 py-2 bg-black text-white rounded-md"
            >
              Next
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
