import Head from 'next/head'
import Image from 'next/image'

import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { getVehicleList, setCurrentPage } from '@/store/vehicle/actions';
import { CarCard } from '@/components';
import { VehicleInterface } from '@/utils/interfaces';

export default function Home() {
  const vehicles = useSelector((state: any) => state.vehicles);
  const currentPage = useSelector((state: any) => state.vehicles.currentPage);
  const totalPages = useSelector((state: any) => state.vehicles.totalPages);

  const bids = useSelector((state: any) => state.bids);

  const itemsPerPage = 5
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(getVehicleList(currentPage));
  }, [dispatch, currentPage]);

  const handlePageChange = (newPage: number) => {
    dispatch(setCurrentPage(newPage));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <div className="text-red p-4">
         

          <div className="grid gap-4 grid-cols-3">
            {vehicles.vehicleList.map((vehicle: VehicleInterface, index: Number) => (
              <CarCard key={vehicle.id} car={vehicle} />
            ))}
          </div>


<button
        onClick={() => handlePageChange(currentPage - 1)}
       // disabled={currentPage === 1}
      >
        Previous
      </button>
      <button
        onClick={() => handlePageChange(currentPage + 1)}
       // disabled={currentPage === totalPages}
      >
        Next
      </button>

        </div>
      </main>
    </>
  )
}
